# Generated by Django 4.0.6 on 2022-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True, max_length=32, null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateField(auto_now_add=True, max_length=32, null=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(max_length=32, verbose_name='注册时间'),
        ),
    ]
