# Generated by Django 4.0.6 on 2022-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_options_user_date_user_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now_add=True, max_length=32, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateField(auto_now=True, max_length=32, null=True, verbose_name='修改日期'),
        ),
    ]
