# Generated by Django 4.0.6 on 2022-07-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_date_alter_user_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update_time',
        ),
    ]
