# Generated by Django 4.0.6 on 2022-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateField(auto_now=True, max_length=32, null=True, verbose_name='修改日期'),
        ),
    ]
