# Generated by Django 4.0.6 on 2022-07-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市')),
            ],
            options={
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_obj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.city', verbose_name='城市id')),
                ('d_obj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.department', verbose_name='部门id')),
            ],
            options={
                'verbose_name_plural': '关系',
            },
        ),
    ]
