# Generated by Django 4.0.6 on 2022-07-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_city_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='d_obj',
            field=models.ManyToManyField(to='app.department'),
        ),
    ]
